name: Release

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A Win32
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VanillaHelpers
          path: |
            build/Release/VanillaHelpers.dll
          if-no-files-found: error

      - name: Attach DLL to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Release/VanillaHelpers.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
